
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jwtsecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        SQL: debug